### ISSUE TITLE
IndieWeb login fails with "File Not Found"

### ISSUE THREAD

**Issue by goodevilgenius** [marksuth/indigenous-android#424]
**Describe the bug**

Adding a new IndieWeb login fails with the message "File Not Found" displayed.

**To Reproduce**
1. Add new account
2. Select IndieWeb
3. Enter site URL
4. Click Sign In
5. Login on website
6. Wait for redirect
7. See "File Not Found"

**Expected behavior**
My account should be added.

**Screenshots**
![Screenshot_20230305-134258](https://user-images.githubusercontent.com/254662/222982326-75de4c9d-6bd4-4dee-bd5c-0586e294f14f.png)

**Smartphone (please complete the following information):**
 - Device: Amazon Fire
 - Android version: Fire OS 7.3.2.7 (I think that's Android 10)

**Additional context**
It seems to be failing because the callback URL is unavailable: https://indigenous.realize.be/indigenous-callback.php

**Comment by marksuth** [comment]
Hi,

This looks like you're running an older version of the app with the previous callback URL, as it should be calling back against https://indigenous.marksuth.dev/indigenous-callback.php.

If you've recently downloaded it, if you could let me know where from and I'll see if I can submit the newer version.

Thanks

**Comment by goodevilgenius** [comment]
@marksuth I downloaded it from F-Droid, which is currently at 0.64

https://f-droid.org/en/packages/com.indieweb.indigenous/

**Comment by ahaasler** [comment]
Hi, I'm having the same problem on 0.64 (latest available on F-Droid). Not happening on 0.65 from Google Play Store. Will 0.65 not be available on F-Droid?

**Comment by marksuth** [comment]
I have just created a tagged release for version 0.66.0 which I'm will be picked up by f-droid and reslove this. I'll keep an eye on it over the next couple of days.

Functionally it's the same as 0.65, just with a few spelling corrections.

**Comment by marksuth** [comment]
Hi, F-droid versions are now back in sync and version 0.84 is available which should resolve this issue for you. If not, just give me a shout and I'll do some more digging.

**Comment by ahaasler** [comment]
Working great, thanks!
