### ISSUE TITLE
F-Droid can't build

### ISSUE THREAD

**Issue by licaon-kter** [marksuth/indigenous-android#433]
ref: https://gitlab.com/fdroid/fdroiddata/-/jobs/4163605483#L282

/LE fyi https://gitlab.com/fdroid/fdroiddata/-/commit/a71ab1fbd7a97a619e39f4d11c4cad1c8a054edf

**Comment by marksuth** [comment]
Thanks for reporting, I can see that versions 0.82 and 0.84 have deployed successfully so I will close this issue.
